services:
  - type: web
    name: cardiorisk-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt && python model.py
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: FRONTEND_URL
        value: https://heart-disease-prediction-zeta.vercel.app
